version: 0.2
run-as: root

phases:

 install:
  commands:
     
   
 pre_build:
   commands:
    - echo Logging in to Amazon EKS...
    
 build:
   commands:
    - composer global require phpunit/phpunit
    - ./vendor/bin/phpunit
    - pwd
    - ls
reports:
  test-report:
    files:
      - build/reports.xml
    file-format: JunitXml
